# Generated by Django 5.0.2 on 2024-02-29 20:03

import month.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdeduction',
            name='period',
            field=month.models.MonthField(),
        ),
    ]
