# Generated by Django 5.0.2 on 2024-03-06 17:06

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=0)),
                ('flag', models.PositiveBigIntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('modtime', models.DateTimeField(auto_now=True)),
                ('attr', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('credit_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
