# Generated by Django 5.0.2 on 2024-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_getcurrentdeduction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filetax',
            index=models.Index(fields=['credit_id'], name='agent_filet_credit__fdf73b_idx'),
        ),
        migrations.AddIndex(
            model_name='filetax',
            index=models.Index(fields=['user_id'], name='agent_filet_user_id_47f5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='getcurrentdeduction',
            index=models.Index(fields=['credit_id'], name='agent_getcu_credit__bd0158_idx'),
        ),
        migrations.AddIndex(
            model_name='getcurrentdeduction',
            index=models.Index(fields=['user_id'], name='agent_getcu_user_id_6af8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='getdeduction',
            index=models.Index(fields=['credit_id'], name='agent_getde_credit__79256c_idx'),
        ),
        migrations.AddIndex(
            model_name='getdeduction',
            index=models.Index(fields=['user_id'], name='agent_getde_user_id_9b6f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='getinvoice',
            index=models.Index(fields=['credit_id'], name='agent_getin_credit__1fcd18_idx'),
        ),
        migrations.AddIndex(
            model_name='getinvoice',
            index=models.Index(fields=['user_id'], name='agent_getin_user_id_ff4a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='getinvoicefile',
            index=models.Index(fields=['credit_id'], name='agent_getin_credit__f65b69_idx'),
        ),
        migrations.AddIndex(
            model_name='getinvoicefile',
            index=models.Index(fields=['user_id'], name='agent_getin_user_id_f72885_idx'),
        ),
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['credit_id'], name='agent_login_credit__654e25_idx'),
        ),
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['user_id'], name='agent_login_user_id_2bf7ea_idx'),
        ),
    ]
