# Generated by Django 5.0.2 on 2024-03-25 13:11

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_filetax_agent_filet_credit__fdf73b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdeduction',
            name='period',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please input valid month like 2024-01', regex='^2\\d{3}-\\d{2}$')]),
        ),
        migrations.CreateModel(
            name='FileVat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=0)),
                ('flag', models.PositiveBigIntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('modtime', models.DateTimeField(auto_now=True)),
                ('attr', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('credit_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['credit_id'], name='agent_filev_credit__8e659b_idx'), models.Index(fields=['user_id'], name='agent_filev_user_id_f89335_idx')],
            },
        ),
    ]
