# Generated by Django 5.0.2 on 2024-03-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_getdeduction_period_filevat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileTax',
        ),
    ]
