# Generated by Django 5.0.2 on 2024-03-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_delete_filetax'),
    ]

    operations = [
        migrations.AddField(
            model_name='filevat',
            name='errcode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filevat',
            name='errmsg',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='getcurrentdeduction',
            name='errcode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getcurrentdeduction',
            name='errmsg',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='getdeduction',
            name='errcode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdeduction',
            name='errmsg',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='getinvoice',
            name='errcode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getinvoice',
            name='errmsg',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='getinvoicefile',
            name='errcode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getinvoicefile',
            name='errmsg',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='login',
            name='errcode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='login',
            name='errmsg',
            field=models.CharField(default='', max_length=512),
        ),
    ]
