# Generated by Django 5.0.2 on 2024-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicing',
            name='business_specific',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='invoicing',
            name='diff_tax',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='invoicing',
            name='reduced_tax',
            field=models.CharField(default='', max_length=512),
        ),
    ]
