# Generated by Django 5.0.2 on 2024-07-10 13:10

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_invoicequota'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=0)),
                ('flag', models.PositiveBigIntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('modtime', models.DateTimeField(auto_now=True)),
                ('attr', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('credit_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('errcode', models.PositiveIntegerField(default=0)),
                ('errmsg', models.CharField(default='', max_length=512)),
                ('sheet_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['credit_id'], name='agent_fileb_credit__a8bdc0_idx'), models.Index(fields=['user_id'], name='agent_fileb_user_id_b53f23_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileCit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=0)),
                ('flag', models.PositiveBigIntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('modtime', models.DateTimeField(auto_now=True)),
                ('attr', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('credit_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('errcode', models.PositiveIntegerField(default=0)),
                ('errmsg', models.CharField(default='', max_length=512)),
                ('begin_staff', models.PositiveIntegerField(default=0)),
                ('end_staff', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['credit_id'], name='agent_filec_credit__d1a608_idx'), models.Index(fields=['user_id'], name='agent_filec_user_id_a5ad3b_idx')],
            },
        ),
    ]
