# Generated by Django 5.0.2 on 2024-07-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_stampduty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampduty',
            name='declaration_type',
            field=models.CharField(default='11|正常申报', max_length=512),
        ),
    ]
