# Generated by Django 5.0.2 on 2025-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_alter_stampduty_declaration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampduty',
            name='is_zero_declaration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
