# Generated by Django 5.0.2 on 2025-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_stampduty_is_zero_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='auth_state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
