# Generated by Django 5.0.2 on 2025-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_login_auth_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='auth_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
