# Generated by Django 5.0.2 on 2025-04-02 11:17

import agent.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_alter_login_auth_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadinvoice',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
    ]
