# Generated by Django 5.0.2 on 2025-04-03 09:01

import agent.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_downloadinvoice_auth_state_alter_login_auth_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdeduction',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getinvoice',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicing',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
    ]
