# Generated by Django 5.0.2 on 2025-04-03 10:54

import agent.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_getdeduction_auth_state_getinvoice_auth_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebsis',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filecit',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filevat',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getcurrentdeduction',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getinvoicefile',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicequota',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revoketax',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stampduty',
            name='auth_state',
            field=agent.fields.MediumTextField(blank=True, null=True),
        ),
    ]
